### ISSUE TITLE
Not working in Modals

### ISSUE THREAD

**Issue by magarrent** [malzariey/filament-daterangepicker-filter#15]
Hey! When you edit/create a record using a separate page it works properly, but when you use a Modal it throws this JS error:

```
dule.esm.js:423 Uncaught ReferenceError: initPickerdays is not defined
    at eval (eval at r (module.esm.js:471:14), <anonymous>:3:16)
    at module.esm.js:489:21
    at Y (module.esm.js:412:12)
    at Function.W (module.esm.js:437:3)
    at module.esm.js:2747:35
    at Function.<anonymous> (module.esm.js:1188:55)
    at n (module.esm.js:575:7)
    at module.esm.js:580:5
    at kt (module.esm.js:773:3)
    at module.esm.js:721:21
```

**Comment by malzariey** [comment]
@magarrent  Please update and confirm if it is solved in v1.2.
